# Generated by Django 4.0.4 on 2022-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1500)),
                ('creation_datetime', models.DateTimeField(null=True)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('video_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
