# Generated by Django 4.0.4 on 2022-04-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_remove_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='long',
        ),
    ]
