# Generated by Django 4.0.4 on 2022-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_remove_customuser_lat_remove_customuser_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('non-binary', 'NON-BINARY'), ('transgender', 'TRANSGENDER'), ('i prefer not to say', 'I PREFER NOT TO SAY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
